#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'countArray' function below.
#
# The function is expected to return a LONG_INTEGER.
# The function accepts following parameters:
#  1. INTEGER n
#  2. INTEGER k
#  3. INTEGER x
#

def countArray(n, k, x):
    # Return the number of ways to fill in the array.
    mod = 10**9 + 7
    if x==1:
        a=[1 for i in range(n)]
        b=[0 for i in range(n)]
    else:
        a=[0 for i in range(n)]
        b=[1 for i in range(n)]
    for i in range(1,n):
        a[i]=b[i-1]% mod
        b[i]=(a[i-1]*(k-1)+b[i-1]*(k-2))% mod
    return a[n-1]
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    first_multiple_input = input().rstrip().split()

    n = int(first_multiple_input[0])

    k = int(first_multiple_input[1])

    x = int(first_multiple_input[2])

    answer = countArray(n, k, x)

    fptr.write(str(answer) + '\n')

    fptr.close()
