#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'cost' function below.
#
# The function is expected to return an INTEGER.
# The function accepts INTEGER_ARRAY B as parameter.
#

def cost(B):
    # Write your code here
    last_is_1=0
    last_is_max=0
    for i in range(1,len(B)):
        last_is_1,last_is_max=max(last_is_1,last_is_max+B[i-1]-1),max(last_is_max+abs(B[i]-B[i-1]),last_is_1+abs(B[i]-1))
    return max(last_is_1,last_is_max)

        
        

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    t = int(input().strip())

    for t_itr in range(t):
        n = int(input().strip())

        B = list(map(int, input().rstrip().split()))

        result = cost(B)

        fptr.write(str(result) + '\n')

    fptr.close()
